services:
  provizora-medio:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bashrc:/home/myself/.bashrc:ro
      - ./zshrc:/home/myself/.zshrc:ro
      - provizora-medio:/home/myself/save

volumes:
  provizora-medio:
